version: '3'
services:
  onlyoffice-mysql-server:
    container_name: onlyoffice-mysql-server
    image: mysql:5.7.31
    environment:
     - MYSQL_ROOT_PASSWORD=my-secret-pw
    networks:
     - onlyoffice
    stdin_open: true
    tty: true
    restart: always
    volumes:
     - ./config/mysql/conf.d:/etc/mysql/conf.d 
     - ./config/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
     - mysql_data:/var/lib/mysql
  onlyoffice-community-server:
    container_name: onlyoffice-community-server
    image: onlyoffice/communityserver:latest
    depends_on:
     - onlyoffice-mysql-server
     # - onlyoffice-document-server
    environment:
     - ONLYOFFICE_CORE_MACHINEKEY=core_secret
     - DOCUMENT_SERVER_PORT_80_TCP_ADDR=onlyoffice-document-server
     - MYSQL_SERVER_ROOT_PASSWORD=my-secret-pw
     - MYSQL_SERVER_DB_NAME=onlyoffice 
     - MYSQL_SERVER_HOST=onlyoffice-mysql-server 
     - MYSQL_SERVER_USER=onlyoffice_user
     - MYSQL_SERVER_PASS=onlyoffice_pass 
    networks:
     - onlyoffice
    ports:
     - '80:80'
     - '443:443'
     - '5222:5222'
    stdin_open: true
    tty: true
    restart: always
    volumes:
     - community_data:/var/www/onlyoffice/Data
     - community_log:/var/log/onlyoffice
     - document_data:/var/www/onlyoffice/DocumentServerData
     - ./certs:/var/www/onlyoffice/Data/certs
  # onlyoffice-document-server:
  #   container_name: onlyoffice-document-server
  #   image: onlyoffice/documentserver:latest
  #   stdin_open: true
  #   tty: true
  #   restart: always
  #   networks:
  #     - onlyoffice
  #   expose:
  #     - '80'
  #     - '443'
  #   volumes:
  #      - document_data:/var/www/onlyoffice/Data
  #      - document_log:/var/log/onlyoffice
  #      - ./document_fonts:/usr/share/fonts/truetype/custom
  #      - document_forgotten:/var/lib/onlyoffice/documentserver/App_Data/cache/files/forgotten
networks:
  onlyoffice:
    driver: 'bridge'
volumes:
  document_data:
  document_log:
  document_forgotten:
  community_data:
  community_log:
  mysql_data:
